{
  "formatVersion": "1.1",
  "component": {
    "group": "simple.lib",
    "module": "hardwarelib",
    "version": "2026.0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hardwarelib-2026.0.8.5.jar",
          "url": "hardwarelib-2026.0.8.5.jar",
          "size": 6620663,
          "sha512": "1e57a05d727829e35a944ec931359debfdf6825b0b8ab56fe549b64a66e04887174d126d5ee5d0414236363fb24e72ee949b02c78a6bf5cea0b6a247afb46bcf",
          "sha256": "f537876b35a167b2d454bc2b2422404225f7930d0bf2387c0f5f717a915171f7",
          "sha1": "831f6a1f3aebc6041177031a1455afafc1c099b7",
          "md5": "288ec12a991696aad9f704f6ef5a6303"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "hardwarelib-2026.0.8.5.jar",
          "url": "hardwarelib-2026.0.8.5.jar",
          "size": 6620663,
          "sha512": "1e57a05d727829e35a944ec931359debfdf6825b0b8ab56fe549b64a66e04887174d126d5ee5d0414236363fb24e72ee949b02c78a6bf5cea0b6a247afb46bcf",
          "sha256": "f537876b35a167b2d454bc2b2422404225f7930d0bf2387c0f5f717a915171f7",
          "sha1": "831f6a1f3aebc6041177031a1455afafc1c099b7",
          "md5": "288ec12a991696aad9f704f6ef5a6303"
        }
      ]
    }
  ]
}
