{
  "formatVersion": "1.1",
  "component": {
    "group": "simple.lib",
    "module": "hardwarelib",
    "version": "2026.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hardwarelib-2026.0.7.jar",
          "url": "hardwarelib-2026.0.7.jar",
          "size": 6820262,
          "sha512": "50421c6ccfcd2ab0a707a96471d327725079330cceb89b44ea2219925d9224c73dd6febed2b439b4d668e59bad97c523c9894015e015ce37e2a496960592a49f",
          "sha256": "802951e1a6871dd4eab88dcdab7eeef43281ea09d64de8be0066d5e6feff6dae",
          "sha1": "690a2b15ae96f576f49482a9db5ce4b7cda5b87d",
          "md5": "9959acafef18ef1f082fe964be36a80b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "org.littletonrobotics.akit",
          "module": "akit-java",
          "version": {
            "requires": "26.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "hardwarelib-2026.0.7.jar",
          "url": "hardwarelib-2026.0.7.jar",
          "size": 6820262,
          "sha512": "50421c6ccfcd2ab0a707a96471d327725079330cceb89b44ea2219925d9224c73dd6febed2b439b4d668e59bad97c523c9894015e015ce37e2a496960592a49f",
          "sha256": "802951e1a6871dd4eab88dcdab7eeef43281ea09d64de8be0066d5e6feff6dae",
          "sha1": "690a2b15ae96f576f49482a9db5ce4b7cda5b87d",
          "md5": "9959acafef18ef1f082fe964be36a80b"
        }
      ]
    }
  ]
}
