{
  "formatVersion": "1.1",
  "component": {
    "group": "simple.lib",
    "module": "hardwarelib",
    "version": "2026.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hardwarelib-2026.0.7.jar",
          "url": "hardwarelib-2026.0.7.jar",
          "size": 6607167,
          "sha512": "da30fd1ebcf73576a2c16013769c376c888f18d622f0480ce1d00564596aa7b0203a434effcce47ff33bddacdbb071880b86ec5a81637eceeeee773c52489ed4",
          "sha256": "913b39cfc10572e3f6ec98a87c3b1a414160ed173cdb4103c94167d36cf7f70c",
          "sha1": "c90f6fdc3deb2e5ff33344e1045ac17edcf7815e",
          "md5": "817fd171d0561b7c57d391ff6dacd4a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "hardwarelib-2026.0.7.jar",
          "url": "hardwarelib-2026.0.7.jar",
          "size": 6607167,
          "sha512": "da30fd1ebcf73576a2c16013769c376c888f18d622f0480ce1d00564596aa7b0203a434effcce47ff33bddacdbb071880b86ec5a81637eceeeee773c52489ed4",
          "sha256": "913b39cfc10572e3f6ec98a87c3b1a414160ed173cdb4103c94167d36cf7f70c",
          "sha1": "c90f6fdc3deb2e5ff33344e1045ac17edcf7815e",
          "md5": "817fd171d0561b7c57d391ff6dacd4a7"
        }
      ]
    }
  ]
}
