{
  "formatVersion": "1.1",
  "component": {
    "group": "simple.lib",
    "module": "hardwarelib",
    "version": "2026.0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hardwarelib-2026.0.8.7.jar",
          "url": "hardwarelib-2026.0.8.7.jar",
          "size": 6598272,
          "sha512": "f0903a30f60a9ee831fda1b991792764228569fb243035bbc0728a1ed3760d5cb9a6426643be7853fc9f6a86cfd91ed14bba54692bafda1adb6c9979bd784f9e",
          "sha256": "0ff462a9d357f068c9d9bef7ee308ffb19e5359814468b09e8e6d8cf90c8fa78",
          "sha1": "6986b68ae5a26b75368cb47bb8f739d97d641ce9",
          "md5": "784b1d6b2c95e4e5aa4551262310d66c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "hardwarelib-2026.0.8.7.jar",
          "url": "hardwarelib-2026.0.8.7.jar",
          "size": 6598272,
          "sha512": "f0903a30f60a9ee831fda1b991792764228569fb243035bbc0728a1ed3760d5cb9a6426643be7853fc9f6a86cfd91ed14bba54692bafda1adb6c9979bd784f9e",
          "sha256": "0ff462a9d357f068c9d9bef7ee308ffb19e5359814468b09e8e6d8cf90c8fa78",
          "sha1": "6986b68ae5a26b75368cb47bb8f739d97d641ce9",
          "md5": "784b1d6b2c95e4e5aa4551262310d66c"
        }
      ]
    }
  ]
}
